
package bos_getattachmentlist_test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BOS_GetAttachmentList_TestService", targetNamespace = "urn:BOS_GetAttachmentList_Test", wsdlLocation = "http://10.240.81.98:8080/arsys/WSDL/public/bmc-bppm/BOS_GetAttachmentList_Test?wsdl")
public class BOSGetAttachmentListTestService
    extends Service
{

    private final static URL BOSGETATTACHMENTLISTTESTSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOSGETATTACHMENTLISTTESTSERVICE_EXCEPTION;
    private final static QName BOSGETATTACHMENTLISTTESTSERVICE_QNAME = new QName("urn:BOS_GetAttachmentList_Test", "BOS_GetAttachmentList_TestService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.240.81.98:8080/arsys/WSDL/public/bmc-bppm/BOS_GetAttachmentList_Test?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOSGETATTACHMENTLISTTESTSERVICE_WSDL_LOCATION = url;
        BOSGETATTACHMENTLISTTESTSERVICE_EXCEPTION = e;
    }

    public BOSGetAttachmentListTestService() {
        super(__getWsdlLocation(), BOSGETATTACHMENTLISTTESTSERVICE_QNAME);
    }

    public BOSGetAttachmentListTestService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOSGETATTACHMENTLISTTESTSERVICE_QNAME, features);
    }

    public BOSGetAttachmentListTestService(URL wsdlLocation) {
        super(wsdlLocation, BOSGETATTACHMENTLISTTESTSERVICE_QNAME);
    }

    public BOSGetAttachmentListTestService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOSGETATTACHMENTLISTTESTSERVICE_QNAME, features);
    }

    public BOSGetAttachmentListTestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BOSGetAttachmentListTestService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PortPortType
     */
    @WebEndpoint(name = "PortSoap")
    public PortPortType getPortSoap() {
        return super.getPort(new QName("urn:BOS_GetAttachmentList_Test", "PortSoap"), PortPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortPortType
     */
    @WebEndpoint(name = "PortSoap")
    public PortPortType getPortSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn:BOS_GetAttachmentList_Test", "PortSoap"), PortPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOSGETATTACHMENTLISTTESTSERVICE_EXCEPTION!= null) {
            throw BOSGETATTACHMENTLISTTESTSERVICE_EXCEPTION;
        }
        return BOSGETATTACHMENTLISTTESTSERVICE_WSDL_LOCATION;
    }

}
