
package bos_getattachmentlist_test;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PortPortType", targetNamespace = "urn:BOS_GetAttachmentList_Test")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PortPortType {


    /**
     * 
     * @param qualification
     * @param startRecord
     * @param maxLimit
     * @return
     *     returns java.util.List<bos_getattachmentlist_test.OutputMapping1.GetListValues>
     */
    @WebMethod(operationName = "GetAttachmentList", action = "urn:BOS_GetAttachmentList_Test/GetAttachmentList")
    @WebResult(name = "getListValues", targetNamespace = "urn:BOS_GetAttachmentList_Test")
    @RequestWrapper(localName = "GetAttachmentList", targetNamespace = "urn:BOS_GetAttachmentList_Test", className = "bos_getattachmentlist_test.InputMapping1")
    @ResponseWrapper(localName = "GetAttachmentListResponse", targetNamespace = "urn:BOS_GetAttachmentList_Test", className = "bos_getattachmentlist_test.OutputMapping1")
    public List<bos_getattachmentlist_test.OutputMapping1 .GetListValues> getAttachmentList(
        @WebParam(name = "Qualification", targetNamespace = "urn:BOS_GetAttachmentList_Test")
        String qualification,
        @WebParam(name = "startRecord", targetNamespace = "urn:BOS_GetAttachmentList_Test")
        String startRecord,
        @WebParam(name = "maxLimit", targetNamespace = "urn:BOS_GetAttachmentList_Test")
        String maxLimit);

}
